spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.dtos"

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
server:
  port: 8083

identity-service:
  url: ${URL_IDENTITY_SERVICE}
