spring:
  application:
    name: IDENTITY-SERVICE

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  # sql:
  #   init:
  #     mode: always
  #     data-locations: classpath:sql/url_access.sql

  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: ${EUREKA_DEFAULT_ZONE}

server:
  port: 9898
