spring:
  application:
    name: IDENTITY-SERVICE

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  sql:
    init:
      mode: always
      data-locations: classpath:sql/url_access.sql

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

server:
  port: 9898
