spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # Cho phép tất cả domain
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: "*" # Cho phép tất cả các header
      routes:
      - id: order-service
#        uri: http://order-service:8081 # Docker
        uri: http://localhost:8081        # Local development
        predicates:
        - Path=/swiggy/**, /orders/**, /vouchers/**
        filters:
        - AuthenticationFilter

      - id: product-service
        uri: http://localhost:8082        # Local development
#        uri: http://product-service:8082 # Docker
        predicates:
        - Path=/products/**
        filters:
        - AuthenticationFilter

      - id: identity-service
        uri: http://localhost:9898        # Local development
#        uri: http://identity-service:9898 # Docker
        predicates:
        - Path=/auth/**, /users/**
        filters:
        - AuthenticationFilter

application:
  name: API-GATEWAY

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_DEFAULT_ZONE}

# spring:
#   application:
#     name: swiggy-gateway
#   cloud:
#     gateway:
#       globalcors:
#         corsConfigurations:
#           '[/**]':
#             allowedOrigins: "*"       # Cho phép tất cả domain
#             allowedMethods:
#               - GET
#               - POST
#               - PUT
#               - DELETE
#               - OPTIONS
#             allowedHeaders: "*"         # Cho phép tất cả các header
#       routes:
#         - id: order-service
#           uri: lb://ORDER-SERVICE
#           predicates:
#             - Path=/swiggy/**, /orders/**
#           filters:
#             - AuthenticationFilter

#         - id: product-service
#           uri: lb://PRODUCT-SERVICE
#           predicates:
#             - Path=/products/**
#           filters:
#             - AuthenticationFilter

#         - id: identity-service
#           uri: lb://IDENTITY-SERVICE
#           predicates:
#             - Path=/auth/**, /users/**
#           filters:
#             - AuthenticationFilter
# eureka:
#   client:
#     service-url:
#       defaultZone: ${EUREKA_DEFAULT_ZONE}
