apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: microsvc
  annotations:
    sidecar.opentelemetry.io/inject: "true"
    instrumentation.opentelemetry.io/inject-java: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: orders-service
        framework: spring

    spec:
      containers:
      - name: orders-service
        image: datnd2711/microsv-order-svc:v2
        env:
        - name: KAFKA_HOST
          value: kafka
        - name: KAFKA_PORT
          value: "9092"
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: javatechie
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: URL_IDENTITY_SERVICE
          value: http://identity-service:9898
        - name: URL_PRODUCT_SERVICE
          value: http://product-service:8082
        ports:
        - containerPort: 8081
          name: http-orders
      imagePullSecrets:
      - name: my-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: microsvc

spec:
  selector:
    app: orders-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: http-orders
