server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
#eureka:
#  client:
#    service-url:
#      defaultZone : ${EUREKA_DEFAULT_ZONE}
