server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

identity-service:
  url: ${URL_IDENTITY_SERVICE}
product-service:
  url: ${URL_PRODUCT_SERVICE}

#eureka:
#  client:
#    service-url:
#      defaultZone : ${EUREKA_DEFAULT_ZONE}
