server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

identity-service:
  url: http://${IDENTITY_SERVICE_URL:localhost}:9898
product-service:
  url: http://${PRODUCT_SERVICE_URL:localhost}:8082
#eureka:
#  client:
#    service-url:
#      defaultZone : ${EUREKA_DEFAULT_ZONE}
