server:
  port: 8082

spring:
  application:
    name: PRODUCT-SERVICE
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/product-db

identity-service:
  url: ${URL_IDENTITY_SERVICE}

#eureka:
#  client:
#    service-url:
#      defaultZone : ${EUREKA_DEFAULT_ZONE}
